### ISSUE TITLE
Suggestion: can we make the dev container work with Podman

### ISSUE THREAD

**Issue by dwhiteddsoft** [eclipse/chariott#34]
On a clean Ubuntu 20+ install with podman toolset used instead of docker, dev container startup fails. Once podman toolset is removed and docker is installed, dev container starts as expected. Is it possible to remove the dependencies on docker to expand to developers who do not want to use a paid for toolset?

**Comment by p-schuler** [comment]
@dariuszparys is looking into this and validates, what it would require.

**Comment by dariuszparys** [comment]
Thanks for submitting this one. I had a brief look at this, in the case of podman you usually use it rootless, the changes to the `devcontainer.json` will result in one that will not start in a regular Docker environment. Here is a work in progress https://github.com/dariuszparys/chariott/blob/chore/podman-support-devcontainer/.devcontainer/devcontainer.json.

I tested this one on Fedora 36, podman rootless and it starts up fine, except for one error message as `podman buildx` doesn't support the version command. The is coming from the [devcontainer cli toolset](https://code.visualstudio.com/docs/devcontainers/devcontainer-cli) that is used in vscode. Beside that error the container is starting up fine with the changes

https://github.com/dariuszparys/chariott/blob/9782759e6d0985ccdcad781beb0725b7b84db54f/.devcontainer/devcontainer.json#L19

and 

https://github.com/dariuszparys/chariott/blob/9782759e6d0985ccdcad781beb0725b7b84db54f/.devcontainer/devcontainer.json#L67-L69

That said, it does not start on a WSL2 installation that is using the default Docker Desktop integration due to the rootless nature. Docker with WSL2 integration does not support the syntax `--userns=keep-id`. Therefore, you would need to uninstall Docker Desktop on Windows and activate `systemd` support for WSL2 as well as install docker inside WSL2 as native runtime. Further you either isolate the container with a user namespace with `--userns-remap` or use the suggested way described here https://docs.docker.com/engine/security/rootless/ to have a rootless experience with docker as well. Anyway, the details are different, and you would end up with two separate `devcontainer.json` files.

Considering all this, I'm not sure how we would have a good out of the box experience after cloning the repo to start-up the devcontainer in vscode. We could provide distinct devcontainer files and have a configuration script to put in the correct one after questioning the dev which container engine is in use, but I feel that might be overkill. What do you think @dwhiteddsoft?

**Comment by dwhiteddsoft** [comment]
The only thing I can think of is to have a script that runs as part of the process that has a large flag/switch logic section based on CPU architecture and maybe platform (in the case of WSL2). I think when we finally get to the resolution of [this issue](https://github.com/eclipse/chariott/issues/35) we are going to need that anyways. @juliays and I are still bottoming out some of the ARM issues.

**Comment by dariuszparys** [comment]
@dwhiteddsoft we updated the README including now some requirements and podman hints.
