### ISSUE TITLE
[QUESTION] Invoking operations on services

### ISSUE THREAD

**Issue by sophokles73** [eclipse/chariott#72]
Hi,
if my understanding of the Chariott service is correct, then I would use the *invoke* intent to call a method on another service that has registered with Chariott.

So let's say my client A wants to invoke method *processData* on service B. Service B provides a spec of its API by means of a protobuf file that also specifies the structure of the data expected as input to *processData*.

Client A would call the Chariott service's *Fullfill* operation via gRPC, passing in an `InvokeIntent` that contains the name of the command to invoke (method *processData* on service B) and the input data to the method. The idea seems to be that a client can easily generate a stub for doing so from Chariott's protobuf definitions. However, these protobuf definitions know nothing about the specific structure of the input data required by proxied service, i.e. the *processData* of service B. Does this mean that a client always needs to *assemble* the input data structure manually when invoking a method on a proxied service? Or is there a way to somehow take advantage of service B's protobuf definition?

**Comment by p-schuler** [comment]
Hi @sophokles73 

You are right, the Chariott API is built so you can express any invoke pattern without actually changing the API. There are multiple ways to get to a more strongly typed representation in your client, if this would be the preferred approach:

1. [We have support for protobuf Any](https://github.com/eclipse/chariott/blob/32676a3228fce96a2f191d654403833a133e2129/proto/chariott/common/v1/common.proto#L136) allowing you to define a schema for the parameters, like we did so in the [dog mode logic example](https://github.com/eclipse/chariott/blob/20584e9935cad5c7d7e8bc90d86a5fdf909ed9b9/examples/applications/dog-mode-logic/src/dog_mode_status.rs#L110-L124). Here we are doing this manually, but the serialization/deserialization logic, could be done by code that is generated using a code generator. 
2. Instead of encoding the message you can do a similar approach using a code generator to use the individual parameters of the Chariott API. Let's say you have a method Add with 2 int as paramters, you can generate the code to pass in `Add` as the name and 2 int as the Values message.  
3. When using `discover` you can access describe custom endpoints and start using them through your custom protobuf definition. To utilize the advantages of Chariott being able to act as a middleware, this is bypassing the API and will take Chariott out of the picture. We see this especially useful to directly switch to a different protocol, like MQTT and for legacy support.

Chariott's API should stay stable to ensure, we can integrate any other APIs without changing the semantics.

**Comment by sophokles73** [comment]
Thanks for the details :-)
ad 1) if I understand correctly, then I would generate two things: first, from the Chariott protobufs, I would generate the Chariott API client stub and second, from the service's protobufs, I would also generate a client stub but would only use the *transfer object* code in order to create a protobuf Any instance that I can pass in to the Chariott client stub's *invoke* method, right?

ad 2) I did not understand what this means/entails.

ad 3) In this case, however, I would effectively loose all checks/assertions that Chariott would usually include like authorization (not yet, of course) etc. and would use Chariott for service (endpoint) discovery only , right?

**Comment by p-schuler** [comment]
1. Yes, that is correct. Just to clarify: there is no automatic binding from the Chariott invoke handling code to your original API. If you would want to call that, you would need to do this manually in the provider handling the invoke, but you could then forward the message you received as is.
2. For example, if you have an Add method in protobuf: 
   ``` 
   rpc Add(AddRequest) returns (AddResponse)
   message AddRequest {
      sint32 n1 = 1;
      sint32 n2 = 2; 
   }
   message AddResponse {
      sint32 result = 1;
   }
   ```
   whereas in Chariott you could re-use the existing invoke API: https://github.com/eclipse/chariott/blob/32676a3228fce96a2f191d654403833a133e2129/proto/chariott/common/v1/common.proto#L112-L124
   and call it (pseudo code) like that:
   ```
   Invoke 'Add' [n1, n2]
   ```
   where the n1 and n2 are the Value message. 
3. Correct.
